CREATE DATABASE Bao_Tang_Quan_Khu_9;
USE Bao_Tang_Quan_Khu_9;

CREATE TABLE NGUOI_DUNG (
    NGUOI_DUNG_ID INT AUTO_INCREMENT PRIMARY KEY,

    -- Đăng nhập
    NGUOI_DUNG_NAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,

    -- Phân loại
    ROLE ENUM('khach', 'huong_dan_vien', 'quan_ly') DEFAULT 'khach',

    -- Trạng thái
    TRANG_THAI ENUM('active', 'inactive', 'banned') DEFAULT 'active',

    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN DATETIME
);

CREATE TABLE NHAN_VIEN (
    NHAN_VIEN_ID INT AUTO_INCREMENT PRIMARY KEY,
    NGUOI_DUNG_ID INT UNIQUE,

    HO_TEN VARCHAR(100) NOT NULL,
    NGAY_SINH DATE,
    GIOI_TINH ENUM('Nam', 'Nu', 'Khac'),

    EMAIL VARCHAR(100) UNIQUE,
    SO_DIEN_THOAI VARCHAR(20),

    AVATAR VARCHAR(255),

    CHUC_VU ENUM('huong_dan_vien', 'quan_ly'),

    NGAY_VAO_LAM DATE,
    LUONG DECIMAL(10,2),

    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (NGUOI_DUNG_ID) REFERENCES NGUOI_DUNG(NGUOI_DUNG_ID)
        ON DELETE CASCADE
);
CREATE TABLE KHU_TRUNG_BAY (
    MA_KHU INT AUTO_INCREMENT PRIMARY KEY,
    TEN_KHU VARCHAR(255),
    MO_TA TEXT
);

CREATE TABLE HIEN_VAT (
    MA_HIEN_VAT INT PRIMARY KEY,
    TEN_HIEN_VAT VARCHAR(255),
    MO_TA TEXT,
    NAM VARCHAR(50),
    NGUON_GOC VARCHAR(255),
    MA_KHU INT,
    FOREIGN KEY (MA_KHU) REFERENCES KHU_TRUNG_BAY(MA_KHU)
);

CREATE TABLE HINH_ANH_HIEN_VAT (
    MA_ANH INT PRIMARY KEY,
    MA_HIEN_VAT INT,
    MO_TA_HIEN_VAT TEXT,
    URL_ANH VARCHAR(255),
    FOREIGN KEY (MA_HIEN_VAT) REFERENCES HIEN_VAT(MA_HIEN_VAT)
        ON DELETE CASCADE
);

CREATE TABLE VIDEO_HIEN_VAT (
    MA_VIDEO  INT PRIMARY KEY,
    MA_HIEN_VAT INT,
    URL_VIDEO VARCHAR(255),
    MO_TA_VIDEO TEXT,
    FOREIGN KEY (MA_HIEN_VAT) REFERENCES HIEN_VAT(MA_HIEN_VAT)
        ON DELETE CASCADE
);

CREATE TABLE MO_TA_HIEN_VAT (
    MA_MO_TA INT PRIMARY KEY,

    MA_HIEN_VAT INT,

    TIEU_DE VARCHAR(255),   -- tiêu đề: Lịch sử, Ý nghĩa...
    NOI_DUNG TEXT,          -- nội dung chi tiết

    THU_TU INT DEFAULT 0,   -- sắp xếp hiển thị

    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (MA_HIEN_VAT) REFERENCES HIEN_VAT(MA_HIEN_VAT)
        ON DELETE CASCADE
);

CREATE TABLE BAI_VIET (
    MA_BAI_VIET INT KEY,

    TIEU_DE VARCHAR(255),
    MO_TA_NGAN TEXT,

    NGAY_DANG DATETIME DEFAULT CURRENT_TIMESTAMP,
    MAUSER INT,

    FOREIGN KEY (MAUSER) REFERENCES NGUOI_DUNG(NGUOI_DUNG_ID)
);

CREATE TABLE BAI_VIET_DOAN (
    MA_DOAN INT PRIMARY KEY,

    MA_BAI_VIET INT,

    TIEU_DE_DOAN VARCHAR(255),
    NOI_DUNG_DOAN TEXT,

    THU_TU INT DEFAULT 0, -- sắp xếp đoạn

    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (MA_BAI_VIET) REFERENCES BAI_VIET(MA_BAI_VIET)
        ON DELETE CASCADE
);

CREATE TABLE HINH_ANH_BAI_VIET (
    MA_ANH INT AUTO_INCREMENT PRIMARY KEY,

    MA_DOAN INT,

    URL_ANH VARCHAR(255) NOT NULL,
    MO_TA VARCHAR(255),

    THU_TU INT DEFAULT 0,

    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (MA_DOAN) REFERENCES BAI_VIET_DOAN(MA_DOAN)
        ON DELETE CASCADE
);

CREATE TABLE VIDEO_BAI_VIET (
    MA_VIDEO INT AUTO_INCREMENT PRIMARY KEY,

    MA_DOAN INT,

    URL_VIDEO VARCHAR(255) NOT NULL,
    TIEU_DE VARCHAR(255),
    MO_TA TEXT,
    THUMBNAIL VARCHAR(255),

    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (MA_DOAN) REFERENCES BAI_VIET_DOAN(MA_DOAN)
        ON DELETE CASCADE
);

CREATE TABLE DANH_GIA (
    MA_DANH_GIA INT AUTO_INCREMENT PRIMARY KEY,

    MA_KHACH INT NOT NULL,
    MA_HIEN_VAT INT NOT NULL,

    NOI_DUNG TEXT,
    SO_SAO INT CHECK (SO_SAO BETWEEN 1 AND 5),

    NGAY_DANH_GIA DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (MA_KHACH) REFERENCES NGUOI_DUNG(NGUOI_DUNG_ID)
        ON DELETE CASCADE,

    FOREIGN KEY (MA_HIEN_VAT) REFERENCES HIEN_VAT(MA_HIEN_VAT)
        ON DELETE CASCADE
);


CREATE TABLE LICH_SU_TIM_KIEM (
    MA_TIM_KIEM INT AUTO_INCREMENT PRIMARY KEY,

    -- Người dùng (bắt buộc phải login)
    MA_KHACH INT NOT NULL,

    -- Ảnh user upload
    ANH_UPLOAD VARCHAR(255),

    -- Kết quả AI trả về
    MA_HIEN_VAT INT,

    -- Độ giống (AI)
    DO_CHINH_XAC FLOAT, -- ví dụ: 0.85

    -- Thời gian
    NGAY_TIM DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (MA_KHACH) REFERENCES NGUOI_DUNG(NGUOI_DUNG_ID)
        ON DELETE CASCADE,

    FOREIGN KEY (MA_HIEN_VAT) REFERENCES HIEN_VAT(MA_HIEN_VAT)
        ON DELETE SET NULL
);





SELECT
    hv.*,
    k.TEN_KHU
FROM HIEN_VAT hv

LEFT JOIN KHU_TRUNG_BAY k
ON hv.MA_KHU = k.MA_KHU



